version: '3'

services:
  certbot-nginx:
    image: node
    env_file: .env
    volumes:
      - .:/slackbot-platform
    restart: always
    command: bash -c "cd /slackbot-platform && npm i && npm start"
