version: '2'

services:
  slackbot-platform:
    image: 'node:lts'
    env_file: .env
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    restart: always
    command: 'npm start'
    depends_on:
      - install
  install:
    image: 'node:lts'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: 'npm i'
