version: '2'

services:
  slackbot-platform:
    image: node:lts
    env_file: .env
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    restart: always
    command: 'npm start'
